// Generated by CoffeeScript 1.6.2
(function() {
  var EcoCompiler, eco;

  eco = require('eco');

  module.exports = EcoCompiler = (function() {
    EcoCompiler.prototype.brunchPlugin = true;

    EcoCompiler.prototype.type = 'template';

    EcoCompiler.prototype.extension = 'eco';

    function EcoCompiler(config) {
      this.config = config;
      null;
    }

    EcoCompiler.prototype.compile = function(data, path, callback) {
      var err, error, result;

      try {
        result = "module.exports = " + (eco.compile(data));
      } catch (_error) {
        err = _error;
        error = err;
      }
      return callback(error, result);
    };

    return EcoCompiler;

  })();

}).call(this);
