// Generated by CoffeeScript 1.6.3
var EcoCompiler, eco, umd;

eco = require('eco');

umd = require('umd-wrapper');

module.exports = EcoCompiler = (function() {
  EcoCompiler.prototype.brunchPlugin = true;

  EcoCompiler.prototype.type = 'template';

  EcoCompiler.prototype.extension = 'eco';

  function EcoCompiler(config) {
    this.config = config;
    null;
  }

  EcoCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result;
    try {
      result = umd(eco.compile(data).toString());
    } catch (_error) {
      err = _error;
      error = err;
    }
    return callback(error, result);
  };

  return EcoCompiler;

})();
